### PR TITLE
Claim issue #702

### LINKED ISSUE #702: Claim issue
Any user can import an issue to Gitpay, but this user maybe is not the author. This feature will allow authors to claim for their issues, so he can gain admin privileges to control assignments and payments.

As the screenshot, you should add a claim button, that will open the dialog to claim the issue. If the user is not logged, requires login first. Please check out other examples one the platform like here:
https://github.com/worknenjoy/gitpay/blob/master/frontend/src/components/task/task.js#L1087

As *Report Issue* #683 , you should first, when the user claims the issue, send an e-mail to who claimed the issue with the following template:
```
You claimed the issue <a href="{{url}}">{{title}}</a> on Gitpay.

You need to be registered on Gitpay with the same Github login from the source repository.

<a href="{{approveURL}}">Claim</a>
```

Once he claims, direct to the application and check if the logged user owns the repo, so he needs to have the same Github user.

For this, you will need to add a `provider_username` on `User` model, so when he does a login with Github, we should fill with the Github username.

If he is not the owner, notify the user. If he's the owner, notify with a successful message and direct to the task.

When the user successfully claims the issue, you should update the `Task` model `User` association.

And the user who initially created the task will receive a notification:

```
The issue <a href="{{url}}">{{title}}</a> you imported on Gitpay was claimed by the author.

So now you don't have admin access to this issue anymore.

Comments: {{comments}}

```

### Why
When someone adds an issue from a repo who belongs to another user, the maintainer should be able to claim in order to control assume the control of the imported issue on Gitpay.

### Level
Medium

### Screenshot attached
Report button

Report dialog

### How to reproduce the user scenario
 - Create a user
 - Import an issue that you're the owner
 - Log with your user
 - You should be able to claim from this point

### What you will need to complete this issue
You will need the Github development keys that will be sent once you're assigned

### PR DESCRIPTION
**Pull request by leonardohof**
## Description

Add the possibility to claim an issue 

## Changes

- Where your changes apply

## Issue

> Closes #702 

## Impacted Area

> Tasks Page

## Steps to test

Steps needed to reproduce the scenario from this change to validate if the pull request solve this issue

- Create a user
- Import an issue that you're the owner
- Log with your user
- Click on "Claim" button

### CODE REVIEW

**Comment by leonardohof** [comment]
@alexanmtz Could you review, please?

**Comment by alexanmtz** [comment]
@leonardohof the code seems right, but I did a test and I received a message that I'm not the author, and I'm the author, so did you tested the main scenario? I will look more in details to figure out why is not working

**Comment by leonardohof** [comment]
> @leonardohof the code seems right, but I did a test and I received a message that I'm not the author, and I'm the author, so did you tested the main scenario? I will look more in details to figure out why is not working

Yes, I did a test creating a issue on my personal GitHub and I imported using a fake account and after that I claim the issue.

We're using a new field to compare the author. Did you login with GitHub? Check with the new field was updated.

**Comment by leonardohof** [comment]
@alexanmtz I tested again and it worked, but I had to logout and login again to update my profile.

File: modules/tasks/taskClaim.js [hunk 1]
```diff
@@ -0,0 +1,74 @@
+const Promise = require('bluebird')
+const taskUpdate = require('./taskUpdate')
+const models = require('../../models')
+const SendMail = require('../mail/mail')
+const i18n = require('i18n')
+const taskFetch = require('./taskFetch')
+
+const sendConfirmationEmail = (task, user, comments) => {
+  const approveURL = `${process.env.FRONTEND_HOST}/#/task/${task.id}/claim/${comments}`
```
Comment (alexanmtz) [inline modules/tasks/taskClaim.js:9]: I think is fragile to use comments as an URL validation.

We should create a kind of token to validate the URL

**Review by alexanmtz — CHANGES_REQUESTED** [review]
@leonardohof we need to review the way you're sending the URL to the application based on the comments.

So check my review.

And I still can't make it work, I'm having an error message even claiming for an issue that I own.

And I could verify that the field you added was updated:
```
response from user find { id: 1,
  ...
  provider_username: 'alexanmtz',
  ... }
```

File: modules/tasks/taskClaim.js (hunk 1 above)
Comment (leonardohof) [reply modules/tasks/taskClaim.js:9]: I made the requested changes.
Could you provide the steps/data you're using to test?

File: modules/tasks/taskClaim.js [hunk 2]
```diff
@@ -22,38 +25,43 @@ const sendConfirmationEmail = (task, user, comments) => {
...
-      await taskUpdate({ id: task.id, userId: user.id })
-
-      const body = `${i18n.__('mail.task.claim.confirmation.body', {
-        title: task.title,
-        url: task.url,
-        comments: comments
-      })}`
+  return jwt.verify(token, process.env.SECRET_PHRASE, async (err, decoded) => {
+    // the 401 code is for unauthorized status
+    if (err || decoded !== task.id) {
```
Comment (alexanmtz) [inline modules/tasks/taskClaim.js:34]:
```suggestion
    if (err || parseInt(decoded) !== parseInt(task.id)) {
```
We need to check both variables converting to numbers, in my case, it was comparing a string and a number

File: modules/tasks/taskClaim.js [hunk 3]
```diff
@@ -22,38 +25,43 @@ const sendConfirmationEmail = (task, user, comments) => {
...
-      return SendMail.success(
-        { email: taskUser.email, language },
-        i18n.__('mail.task.claim.confirmation.subject'), body
-      )
+    if (task.provider !== 'github' || user.provider !== task.provider) {
+      throw new Error('invalid_provider')
     }
-    else {
+
+    if (task.metadata.user !== user.provider_username) {
```
Comment (alexanmtz) [inline modules/tasks/taskClaim.js:42]:
```suggestion
    if (task.metadata.issue.user.login !== user.provider_username) {
```

In my case, the `task.metadata.user` it was the organization, so that's why its not working. I suggest checking the issue author instead.

**Review by alexanmtz — CHANGES_REQUESTED** [review]
great @leonardohof 👍 

we're almost there. I could find now the reason my tests didn't succeed and I've made suggestions in order to fix, and then I think we will be good to go.

Great solution for the token part 🥇

**Comment by leonardohof** [comment]
> great @leonardohof 👍
> 
> we're almost there. I could find now the reason my tests didn't succeed and I've made suggestions in order to fix, and then I think we will be good to go.
> 
> Great solution for the token part 🥇

Great!
I applied the suggestions and tested it locally and It worked!

**Review by alexanmtz — APPROVED** [review]
