### PR TITLE
User roles

### LINKED ISSUE #532: Define user role
We want to define user roles when they register and as part of the account settings

### Why
We want to know the user roles to offer a more optimized experience (Later on)

### Level
Medium

### Current behavior
We create a user, and this user is generic

### Expected behavior
The user should have multiple roles 

### Screenshot attached
role-page-config
role-page

### Assets
icon-maintain
icon-contribution
icon-funding

### How to reproduce the user scenario
 - Create a user
 - A screen will ask to define user roles
 - We should record the current user role
 - We should have a page in preferences to change user roles

### Tips
Create table `roles` and a user can have multiple roles

### PR DESCRIPTION
**Pull request by namandangi**
## Description

> Add a new page to manage user roles

## Changes

- new :
        /frontend/src/actions/userRoleActions.js
        /frontend/src/components/profile/user-roles.js
        /frontend/src/reducers/userRoleReducers.js
        /modules/app/controllers/userRole.js
        /modules/app/routes/userRole.js
        /modules/userRoles/userRoleFetch.js
        /modules/userRoles/userRoleCreate.js
        /modules/userRoles/userRoleDelete.js
        /models/userRole.js

- modified :
        /frontend/src/containers/profile.js
        /frontend/src/components/profile/profile.js
        /frontend/src/reducers/reducers.js
        /models/user.js
        /modules/app/index.js
        /modules/roles/index.js

## Issue

> Closes #532

## Impacted Area

> /profile/roles

## Steps to test

Steps needed to reproduce the scenario from this change to validate if the pull request solve this issue

- Create / log user
- Visit the user roles page at '/profile/roles'

image

image
image

### CODE REVIEW

File: models/userRole.js [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+      }
+    }
+  }, {
+    classMethods: {
+      associate: (models) => {
+        UserRole.belongsTo(models.User, { foreignKey: 'userId' })
+      }
+    },
+    instanceMethods: {
+
```
Comment (alexanmtz) [inline models/userRole.js:24]: You need to create another migration with the `Role` table, and the role contains the name, and then on this migration, we reference the `roleId` 

The way you implemented we will have a new role for each user, and that's not what we want, we want to have defined roles and reference the user to that role.

But now if you give a `Role` table, it will affect the Member Roles table, so we need another name.

We can call `UserTypes` with a table `Types`, or `UserViews` with a table `Views`

Or we rename the Roles for Members.

**Comment by alexanmtz** [comment]
@namandangi you will continue on this? It's been a while without any activity

**Comment by namandangi** [comment]
> @namandangi you will continue on this? It's been a while without any activity

Yeah I'll resume working on this from next week once I have sorted my academics out

**Review by alexanmtz — APPROVED** [review]

**Comment by alexanmtz** [comment]
@namandangi I will proceed and approve the front-end changes and I updated the branch removing the back-end changes, and we will create an issue just for that in the future.

**Comment by namandangi** [comment]
> @namandangi I will proceed and approve the front-end changes and I updated the branch removing the back-end changes, and we will create an issue just for that in the future.

Thanks for approving the frontend!
