### PR TITLE
Issue#840

### LINKED ISSUE #840: Direct payments support for Brazilian accounts
From Stripe:
"Transfers cannot be sent to accounts located in Brazil because it's outside of your platform's region. Create a destination or direct payment in order to add funds to this account's balance."

### Why
We have many active accounts in Brazil that will not be able to receive payments for bounties if is not direct payments

### Level
Medium

### Current behavior
When a payment is made for a task, it's sent for the Stripe funds, so it's not possible to transfer to a Brazilian account.

### Expected behavior
When payment for a bounty is created, we should be able to set the destination account for the assigned user if the user-activated account is from Brazil.

### Useful links
  - Github API: https://docs.github.com/en/rest
  - Material-UI: https://material-ui.com/
  - Stripe API for charges and transfers: https://stripe.com/docs/connect/charges-transfers

### Screenshot attached
Screenshot
Description

### How to reproduce the user scenario
- Scenario 1
   - Run the project locally
   - Create a user
   - Import an issue
   - Make a payment

### What you will need to complete this issue
- Stripe development keys to create payments

### Tips
- All the UI will use Material UI (https://material-ui.com/)
- Use our translation library Run `npm run translate` on the `/frontend` folder to sync translation before sending the PR

### PR DESCRIPTION
**Pull request by VictorAlessander**
## Description

> Fixing issue with `transferGroup` param value going null to stripe. This causes a error response from stripe and the transfer isn't finished.

## Changes

- Task payment - Stripe Transfer

## Issue

> Closes #840 (already closed)

## Impacted Area

> Task Payments

## Steps to test

Steps needed to reproduce the scenario from this change to validate if the pull request solve this issue

- Create / log user
- Create Task
- Try to pay the task using a 100% coupon using a credit card (stripe)

### CODE REVIEW

File: modules/tasks/taskPayment.js [hunk 1]
```diff
@@ -27,14 +27,7 @@ module.exports = Promise.method(function taskPayment (paymentParams) {
...
 
-        let transferGroup = null
-
-        const order = await models.Order.findOne({ where: { TaskId: task.id } })
-        const coupon = await models.Coupon.findOne({ where: { id: order.couponId } })
-
-        if (!coupon || (coupon && coupon.amount < 100)) {
-          transferGroup = task.transfer_group ? task.transfer_group : `task_${task.id}`
-        }
+        const transferGroup = task.transfer_group ? task.transfer_group : `task_${task.id}`
```
Comment (alexanmtz) [inline modules/tasks/taskPayment.js:30]: @VictorAlessander with this solution the error maybe will persist in some cases.

For coupon with 100% the transfer group shouldn't be sent, so the way it before made sense, the error is that you're sending empty, and the rule here is it will not send the parameter if is empty.

So maybe you initialize the transfer params object first like:

```
let transferData = {
          amount: centavosAmount * 0.92, // 8% base fee
          currency: 'usd',
          destination: dest,
          source_type: 'card'
        }
``` 

And on the if clause you may add:

`transferData.transferGroup = ...`

So it will only define `transferGroup` inside the condition

**Review by alexanmtz — CHANGES_REQUESTED** [review]
@VictorAlessander actually this solution you removed will cause an error, and I suggested a solution that we can deal with the case that is sending a empty transfer group, and in this case we need to remove the key.

**Comment by alexanmtz** [comment]
Great @VictorAlessander 🎉

**Review by alexanmtz — APPROVED** [review]
