### PR TITLE
fixed Images overlaps on Issue page description, corrected the style and also make it responsiv…

### LINKED ISSUE #1199: [Bug]: Images overlaps on Issue page description
### Contact Details

issues@gitpay.me

### What happened?

As you can see on the Screenshot, big images overlap the content of the description
Image

To run the project locally, you can follow your README: https://github.com/worknenjoy/gitpay?tab=readme-ov-file#readme

Steps to reproduce
- Follow our README to run the project locally
- Register a user
- Import an issue with images
- You will see the issue created with overlaping images

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
We use Marked and Parse to render the description.
https://www.npmjs.com/package/marked
https://www.npmjs.com/package/parse

Feel free to replace the library with something that handles high-resolution images better.
```

### 💰 Is there a bounty for this issue?

No

### 💵 Bounty Amount (if any)

No bounty for this one

### 📜 Bounty Details (if applicable)

There's no Bounty for this issue.

This issue is part of the Only Dust Hackathon: https://onlydust.notion.site/May-28th-Open-Source-Hackathon-1f244b682a80801890e5fda15b779746

### PR DESCRIPTION
**Pull request by perpetual-cosmos**
maintain the cleaner code

# Pull Request Template

> Closes #1199 

## Description
The issue with large images overlapping the description content has been resolved by making targeted CSS and layout adjustments. Specifically, we set align-items: flex-start on the parent grid container of the right column to ensure it stretches only to fit its content rather than the full screen height. Additionally, we tweaked relevant Material-UI component properties to improve responsiveness and properly handle overflow across all screen sizes. These changes were carefully implemented to fix the layout issues while preserving existing functionality, with minimal modifications to the codebase. The result is a clean, responsive design that displays large images without breaking the layout.

## Purpose
To fix the layout issue where large images in issue descriptions overlap the surrounding content. This was observed when rendering markdown with the marked and parse libraries. The goal was to ensure images display correctly and responsively across all screen sizes, without altering the core functionality or replacing existing libraries.

## Solution
-Updated the parent container of the right column in the grid layout by setting align-items: flex-start, ensuring the column stretches only to fit its content rather than occupying the full height of the screen.
- Added `className` prop to `IssueContent` and applied it to the `<Typography>` component to handle text overflow (e.g., long HTTPS links) by applying `wordBreak: 'break-word'` and `overflowWrap: 'break-word'`.
- Updated `Task.js` styles (`issueContent`) to constrain images with `maxWidth: '100%'` to prevent overlap.
- Fixed right column alignment on mobile screens using responsive styles.

## Screenshots
image
image
image
image

## Checklist
- [x] Code has been tested and works as intended
- [x] Properly documented code
- [x] Follows coding standards and guidelines
- [x] All tests pass
- [x] No conflicts with current codebase
- [x] Code has been reviewed by at least one other team member

## Related Issues
Link any related issues that this pull request addresses.

## Additional Notes
II really enjoyed working on this issue—thank you for the opportunity. I’ve done my best to implement a clean and effective solution, ensuring the layout works well across all screens. If there’s any feedback or further improvements needed, I’d be happy to make the changes promptly. Please feel free to reach out if any other issues come up—I’ll be glad to help without delay. Thank you once again!

### CODE REVIEW

**Comment by perpetual-cosmos** [comment]
Thanks for the quick review and the kind words!

Yes, I'll definitely look into both adjustments: moving the styles to issue-content.tsx and correcting the extra formatting. I'll get those updated as soon as possible.

Thanks again for the clear feedback!

File: frontend/src/components/areas/public/features/task/task.js [hunk 1]
```diff
@@ -864,9 +914,10 @@ class Task extends Component {
         {noTopBar ? null : (
           <TopBarContainer />
         )}
-        <Grid container style={{ marginBottom: 4 }}>
+        <Grid container style={{ marginBottom: 4 }} alignItems="flex-start">
```
Comment (alexanmtz) [inline frontend/src/components/areas/public/features/task/task.js]:
```suggestion
        <Grid container style={{ marginBottom: 4 }} alignItems="stretch">
```

**Review by alexanmtz — COMMENTED** [review]
Now looks great @perpetual-cosmos , just an adjustment on the alignItems property, because we want that the right Sidebar follows the content.

**Comment by perpetual-cosmos** [comment]
Thanks for merging! Noted on the alignItems tweak — I'll open a follow-up PR to address that

**Comment by alexanmtz** [comment]
Hey @perpetual-cosmos , no problem, I commited to your PR merged the adjustment, so all good to release 🚀

**Comment by perpetual-cosmos** [comment]
Awesome, thanks so much for taking care of that! 🚀 Glad to hear it's all set for release 🙌
