### PR TITLE
Issue#840 - Direct payments support for Brazilian accounts

### LINKED ISSUE #840: Direct payments support for Brazilian accounts
From Stripe:
"Transfers cannot be sent to accounts located in Brazil because it's outside of your platform's region. Create a destination or direct payment in order to add funds to this account's balance."

### Why
We have many active accounts in Brazil that will not be able to receive payments for bounties if is not direct payments

### Level
Medium

### Current behavior
When a payment is made for a task, it's sent for the Stripe funds, so it's not possible to transfer to a Brazilian account.

### Expected behavior
When payment for a bounty is created, we should be able to set the destination account for the assigned user if the user-activated account is from Brazil.

### Useful links
  - Github API: https://docs.github.com/en/rest
  - Material-UI: https://material-ui.com/
  - Stripe API for charges and transfers: https://stripe.com/docs/connect/charges-transfers

### Screenshot attached
Screenshot
Description

### How to reproduce the user scenario
- Scenario 1
   - Run the project locally
   - Create a user
   - Import an issue
   - Make a payment

### What you will need to complete this issue
- Stripe development keys to create payments

### Tips
- All the UI will use Material UI (https://material-ui.com/)
- Use our translation library Run `npm run translate` on the `/frontend` folder to sync translation before sending the PR

### PR DESCRIPTION
**Pull request by VictorAlessander**
## Description

> Changes in webhook update for charge succeeded case.

## Changes

- controllers/webhook.js
- test/webhook.test.js
- modules/chargeSucceeded.js (new file)

## Issue

> Closes #840

## Impacted Area

> Webhook update

## Steps to test

Steps needed to reproduce the scenario from this change to validate if the pull request solve this issue

- Build the test containers (services)
- Run the test seeds
- Run webhooks tests

image

### CODE REVIEW

File: modules/app/controllers/webhook.js [hunk 1]
```diff
@@ -377,53 +379,7 @@ exports.updateWebhook = (req, res) => {
...
-                  return res.status(400).send(e)
-                })
-            }
-          })
-          .catch(e => {
-            return res.status(400).send(e)
-          })
-
-        break
+        return chargeSucceeded(event, paid, status, req, res)
```
Comment (alexanmtz) [inline modules/app/controllers/webhook.js:382]: @VictorAlessander That's an amazing refactoring 🎉 

We can use this solution to split all webhook calls in modules 👍

**Comment by alexanmtz** [comment]
Amazing @VictorAlessander 🎉
