### PR TITLE
fix: issue with loader

### LINKED ISSUE #502: Error 404 and 500
Handle some 404 and 500 errors:
- Handle error 404 when access a task not found
- Handle error 500 from newly created accounts with a notification: "There's was an error to process your request"

### Why
We have an empty screen or crash in those situations that we need to handle gracefully

### Level
Beginner

### Current behavior
We're not handling properly error 404 and 500 when access a task and when a user bank account is activated.

### Expected behavior
For 404 page, we expect a simple 404 page (a page with a header and a big 404 in the center) and a text _Not found_

### How to reproduce the user scenario

 - Create a user
 - Try to activate account (locally you will probably will get an error 500)
 - Try to access an undefined task like http://gitpay.me/#/task/any-thing

### PR DESCRIPTION
**Pull request by ShubhamCanMakeCommit**
## Description

> Merge issue with loader component

## Changes

- task.js

## Issue

> Closes #502 

## Impacted Area

> Main page

## Steps to test

Steps needed to reproduce the scenario from this change to validate if the pull request solve this issue

- Create / log user
- Create Task
- Other steps

### CODE REVIEW

File: frontend/src/components/task/task.js [hunk 1]
```diff
@@ -693,9 +693,6 @@ class Task extends Component {
       this.props.history.push('/404')
       return null
     }
-    if (!task.completed) {
-      return (<div />)
-    }
```
Comment (ShubhamCanMakeCommit) [inline frontend/src/components/task/task.js:698]: I actually wanted to render a empty screen when the task didn't get rendered. But now we have a loader that's completely unnecessary so removed it.

**Comment by alexanmtz** [comment]
Great @ShubhamCanMakeCommit , let's merge it 👍
